version: '3'
services:
  jaeger:
    # Jaeger is one of many options we can choose from as our distributed tracing backend.
    # It supports OTLP out of the box so it's very easy to get started.
    # https://www.jaegertracing.io
    image: jaegertracing/all-in-one
    ports:
      - "4317:4317" # This is where the OTLPGRPCSpanExporter sends its spans
      - "16686:16686" # This is Jaeger's Web UI, visualizing recorded traces
