receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "127.0.0.1:4317"

exporters:
  file:
    path: /home/runner/work/swift-otel/swift-otel/IntegrationTests/otel-collector-output.jsonl

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [file]

# yaml-language-server: $schema=https://raw.githubusercontent.com/srikanthccv/otelcol-jsonschema/main/schema.json
