receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "otel-collector:4317"

exporters:
  debug:
    verbosity: detailed
  file:
    path: /etc/otelcol-contrib/output/output.jsonl

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, file]

# yaml-language-server: $schema=https://raw.githubusercontent.com/srikanthccv/otelcol-jsonschema/main/schema.json
