scrape_configs:
  - job_name: "otel-collector"
    scrape_interval: 5s
    static_configs:
      - targets: ["otel-collector:7070"]

# yaml-language-server: $schema=http://json.schemastore.org/prometheus
