name: Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          format: html
          base-url: /swift-otel/
          module-name: "OpenTelemetry Swift"
          output: Documentation

      - name: Update Permissions
        run: 'sudo chown -R $USER Documentation'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: Documentation
